In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/heart.csv")

In [ ]:
df

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     29    1   1       130   204    0  ...      0      0.0      2   0     2       1
1     34    1   3       118   182    0  ...      0      0.0      2   0     2       1
2     34    0   1       118   210    0  ...      0      0.7      2   0     2       1
3     35    0   0       138   183    0  ...      0      1.4      2   0     2       1
4     35    1   1       122   192    0  ...      0      0.0      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   71    0   2       110   265    1  ...      0      0.0      2   1     2       1
299   71    0   0       112   149    0  ...      0      1.6      1   0     2       1
300   74    0   1       120   269    0  ...      1      0.2      2   1     2       1
301   76    0   2       140   197    0  ...      0      1.1      1   0     2       1
302   77    1   0       125   304    0  ...      1      0.0      2   3     2       0

[303 rows x 14 columns]

In [ ]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1:]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.to_numpy()

array([[54.,  1.,  1., ...,  2.,  0.,  3.],
       [59.,  1.,  3., ...,  0.,  0.,  3.],
       [58.,  0.,  1., ...,  2.,  2.,  2.],
       ...,
       [51.,  1.,  0., ...,  1.,  3.,  3.],
       [66.,  0.,  3., ...,  0.,  0.,  2.],
       [51.,  1.,  2., ...,  1.,  0.,  2.]])

In [ ]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(242, 13) (61, 13) (242, 1) (61, 1)


In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
mlp = MLPClassifier()

In [ ]:
parameter_space = {
    'max_iter':[100, 150, 200],
    'hidden_layer_sizes': [(50,50,50), (50,100,50), (70,70,70)],
    'activation': ['identity', 'tanh', 'relu'],
    'solver': ['sgd', 'adam', 'lbfgs'],
    'alpha': [0.1, 0.01, 0.001, 0.0001],
    'learning_rate': ['constant','adaptive','invscaling'],
}

In [ ]:
clf = GridSearchCV(mlp, parameter_space, n_jobs=-1, cv=3)
clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (150) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


GridSearchCV(cv=3, error_score=nan,
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_fun=15000,
                                     max_iter=200, momentum=0.9,
                                     n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state...
             iid='deprecated', n_jobs=-1,
             param_grid={'activation': ['identity', 'tanh', 'relu'],
                         'alpha': [0.1, 0.01, 0.001, 0.0001],
                         'hidden_layer_sizes': [(50, 50, 50), (50, 100, 50),
                                

In [ ]:
# Best paramete set
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'constant', 'max_iter': 150, 'solver': 'sgd'}


In [ ]:
y_pred = clf.predict_proba(X_test)[:,1]

In [ ]:
y_pred = np.array([1 if y_>0.5 else 0 for y_ in y_pred])
y_pred

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
y_test.to_numpy().ravel()

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
print(classification_report(y_test.to_numpy().ravel(), y_pred)) #[1 if y_>0.5 else 0 for y_ in y_pred]

              precision    recall  f1-score   support

           0       0.87      0.81      0.84        32
           1       0.81      0.86      0.83        29

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

